In [63]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [64]:
studentVle = pd.read_csv("../Dataset/processed/studentVle_clean.csv")

studentAssessment = pd.read_csv("../Dataset/processed/studentAssessment_clean.csv")

assessments = pd.read_csv("../Dataset/processed/assessments_clean.csv")

studentInfo = pd.read_csv("../Dataset/processed/studentInfo_clean.csv")

In [65]:
print(studentVle.shape)
print(studentAssessment.shape)
print(assessments.shape)
print(studentInfo.shape)

(10655280, 7)
(173912, 5)
(206, 6)
(32593, 13)

In [66]:
studentVle["week"] = ((studentVle["date"] - studentVle["date"].min()) // 7) + 1

In [67]:
weekly_clicks = (
    studentVle
    .groupby(
        ["id_student", "code_module", "code_presentation", "week"]
    )["sum_click"]
    .sum()
    .reset_index()
)

weekly_clicks.rename(
    columns={"sum_click": "weekly_video_clicks"},
    inplace=True
)

weekly_clicks.head()

   id_student code_module code_presentation  week  weekly_video_clicks
0        6516         AAA             2014J     1                  151
1        6516         AAA             2014J     2                    9
2        6516         AAA             2014J     3                   31
3        6516         AAA             2014J     4                  241
4        6516         AAA             2014J     5                   56

In [68]:
weekly_login = (
    studentVle
    .groupby(
        [
            "id_student",
            "code_module",
            "code_presentation",
            "week"
        ]
    )["date"]
    .nunique()
    .reset_index()
)

weekly_login.rename(
    columns={
        "date":"weekly_login_frequency"
    },
    inplace=True
)

weekly_login.head()

   id_student code_module code_presentation  week  weekly_login_frequency
0        6516         AAA             2014J     1                       3
1        6516         AAA             2014J     2                       2
2        6516         AAA             2014J     3                       2
3        6516         AAA             2014J     4                       5
4        6516         AAA             2014J     5                       4

In [69]:
weekly_activity = (
    studentVle
    .groupby(
        [
            "id_student",
            "code_module",
            "code_presentation",
            "week"
        ]
    )["date"]
    .mean()
    .reset_index()
)

weekly_activity.rename(
    columns={
        "date":"weekly_avg_activity_day"
    },
    inplace=True
)

weekly_activity.head()

   id_student code_module code_presentation  week  weekly_avg_activity_day
0        6516         AAA             2014J     1               -21.280000
1        6516         AAA             2014J     2               -15.333333
2        6516         AAA             2014J     3                -5.333333
3        6516         AAA             2014J     4                -0.081081
4        6516         AAA             2014J     5                 5.333333

In [70]:
assessment_data = pd.merge(
    studentAssessment,
    assessments,
    on="id_assessment",
    how="left"
)

assessment_data.head()

,id_assessment,id_student,date_submitted,is_banked,score,code_module,code_presentation,assessment_type,date,weight
0,1752,11391,18,0,78.0,AAA,2013J,TMA,19.0,10.0
1,1752,28400,22,0,70.0,AAA,2013J,TMA,19.0,10.0
2,1752,31604,17,0,72.0,AAA,2013J,TMA,19.0,10.0
3,1752,32885,26,0,69.0,AAA,2013J,TMA,19.0,10.0
4,1752,38053,19,0,79.0,AAA,2013J,TMA,19.0,10.0

In [71]:
assessment_data["week"] = (
    (assessment_data["date_submitted"] - assessment_data["date_submitted"].min()) // 7
) + 1

In [72]:
weekly_quiz = (

    assessment_data

    .groupby(

        [
            "id_student",
            "code_module",
            "code_presentation",
            "week"
        ]

    )["score"]

    .mean()

    .reset_index()

)

weekly_quiz.rename(

    columns={

        "score":"weekly_avg_quiz_score"

    },

    inplace=True

)

weekly_quiz.head()

   id_student code_module code_presentation  week  weekly_avg_quiz_score
0        6516         AAA             2014J     5                   60.0
1        6516         AAA             2014J     9                   48.0
2        6516         AAA             2014J    19                   63.0
3        6516         AAA             2014J    26                   61.0
4        6516         AAA             2014J    32                   77.0

In [73]:
weekly_submission = (

    assessment_data

    .groupby(
        [
            "id_student",
            "code_module",
            "code_presentation",
            "week"
        ]
    )["date_submitted"]

    .mean()

    .reset_index()

)

weekly_submission.rename(
    columns={
        "date_submitted":"weekly_avg_submission_day"
    },
    inplace=True
)

weekly_submission.head()

   id_student code_module code_presentation  week  weekly_avg_submission_day
0        6516         AAA             2014J     5                       17.0
1        6516         AAA             2014J     9                       51.0
2        6516         AAA             2014J    19                      116.0
3        6516         AAA             2014J    26                      164.0
4        6516         AAA             2014J    32                      210.0

In [74]:
weekly_weight = (

    assessment_data

    .groupby(
        [
            "id_student",
            "code_module",
            "code_presentation",
            "week"
        ]
    )["weight"]

    .mean()

    .reset_index()

)

weekly_weight.rename(
    columns={
        "weight":"weekly_avg_assessment_weight"
    },
    inplace=True
)

weekly_weight.head()

,id_student,code_module,code_presentation,week,weekly_avg_assessment_weight
0,6516,AAA,2014J,5,10.0
1,6516,AAA,2014J,9,20.0
2,6516,AAA,2014J,19,20.0
3,6516,AAA,2014J,26,20.0
4,6516,AAA,2014J,32,30.0

In [75]:
weekly_assessment = (

    assessment_data

    .groupby(

        [
            "id_student",
            "code_module",
            "code_presentation",
            "week"
        ]

    )

    .size()

    .reset_index(name="weekly_assessments_completed")

)

weekly_assessment.head()

,id_student,code_module,code_presentation,week,weekly_assessments_completed
0,6516,AAA,2014J,5,1
1,6516,AAA,2014J,9,1
2,6516,AAA,2014J,19,1
3,6516,AAA,2014J,26,1
4,6516,AAA,2014J,32,1

In [76]:
weekly_data = pd.merge(
    weekly_clicks,
    weekly_login,
    on=["id_student","code_module","code_presentation","week"],
    how="left"
)

weekly_data = pd.merge(
    weekly_data,
    weekly_activity,
    on=["id_student","code_module","code_presentation","week"],
    how="left"
)

weekly_data = pd.merge(
    weekly_data,
    weekly_quiz,
    on=["id_student","code_module","code_presentation","week"],
    how="left"
)

weekly_data = pd.merge(
    weekly_data,
    weekly_assessment,
    on=["id_student","code_module","code_presentation","week"],
    how="left"
)

weekly_data = pd.merge(
    weekly_data,
    weekly_submission,
    on=["id_student","code_module","code_presentation","week"],
    how="left"
)

weekly_data = pd.merge(
    weekly_data,
    weekly_weight,
    on=["id_student","code_module","code_presentation","week"],
    how="left"
)

In [77]:
weekly_data = pd.merge(

    weekly_data,

    studentInfo[

        [

            "id_student",

            "code_module",

            "code_presentation",

            "dropout"

        ]

    ],

    on=[

        "id_student",

        "code_module",

        "code_presentation"

    ],

    how="left"

)

In [78]:
weekly_data.fillna({

    "weekly_avg_quiz_score":0,

    "weekly_assessments_completed":0,

    "weekly_login_frequency":0,

    "weekly_avg_activity_day":0,

    "weekly_avg_submission_day":0,

    "weekly_avg_assessment_weight":0

}, inplace=True)

,id_student,code_module,code_presentation,week,weekly_video_clicks,weekly_login_frequency,weekly_avg_activity_day,weekly_avg_quiz_score,weekly_assessments_completed,weekly_avg_submission_day,weekly_avg_assessment_weight,dropout
0,6516,AAA,2014J,1,151,3,-21.280000,0.0,0.0,0.0,0.0,0
1,6516,AAA,2014J,2,9,2,-15.333333,0.0,0.0,0.0,0.0,0
2,6516,AAA,2014J,3,31,2,-5.333333,0.0,0.0,0.0,0.0,0
3,6516,AAA,2014J,4,241,5,-0.081081,0.0,0.0,0.0,0.0,0
4,6516,AAA,2014J,5,56,4,5.333333,60.0,1.0,17.0,10.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
630028,2698588,BBB,2014J,37,107,3,231.743590,0.0,0.0,0.0,0.0,0
630029,2698588,BBB,2014J,38,62,6,236.818182,0.0,0.0,0.0,0.0,0
630030,2698588,BBB,2014J,39,3,1,244.000000,0.0,0.0,0.0,0.0,0
630031,2698588,BBB,2014J,40,7,2,249.000000,0.0,0.0,0.0,0.0,0
630032,2698588,BBB,2014J,41,1,1,258.000000,0.0,0.0,0.0,0.0,0

In [79]:
weekly_data = weekly_data.sort_values(

    [

        "id_student",

        "week"

    ]

)

weekly_data.head()

,id_student,code_module,code_presentation,week,weekly_video_clicks,weekly_login_frequency,weekly_avg_activity_day,weekly_avg_quiz_score,weekly_assessments_completed,weekly_avg_submission_day,weekly_avg_assessment_weight,dropout
0,6516,AAA,2014J,1,151,3,-21.280000,0.0,0.0,0.0,0.0,0
1,6516,AAA,2014J,2,9,2,-15.333333,0.0,0.0,0.0,0.0,0
2,6516,AAA,2014J,3,31,2,-5.333333,0.0,0.0,0.0,0.0,0
3,6516,AAA,2014J,4,241,5,-0.081081,0.0,0.0,0.0,0.0,0
4,6516,AAA,2014J,5,56,4,5.333333,60.0,1.0,17.0,10.0,0

In [80]:
print(weekly_data.shape)
print(weekly_data.columns)
weekly_data.head()

(630033, 12)
Index(['id_student', 'code_module', 'code_presentation', 'week',
       'weekly_video_clicks', 'weekly_login_frequency',
       'weekly_avg_activity_day', 'weekly_avg_quiz_score',
       'weekly_assessments_completed', 'weekly_avg_submission_day',
       'weekly_avg_assessment_weight', 'dropout'],
      dtype='str')

,id_student,code_module,code_presentation,week,weekly_video_clicks,weekly_login_frequency,weekly_avg_activity_day,weekly_avg_quiz_score,weekly_assessments_completed,weekly_avg_submission_day,weekly_avg_assessment_weight,dropout
0,6516,AAA,2014J,1,151,3,-21.280000,0.0,0.0,0.0,0.0,0
1,6516,AAA,2014J,2,9,2,-15.333333,0.0,0.0,0.0,0.0,0
2,6516,AAA,2014J,3,31,2,-5.333333,0.0,0.0,0.0,0.0,0
3,6516,AAA,2014J,4,241,5,-0.081081,0.0,0.0,0.0,0.0,0
4,6516,AAA,2014J,5,56,4,5.333333,60.0,1.0,17.0,10.0,0

In [81]:
df = pd.read_csv("../Dataset/weekly_student_dataset.csv")

print(df.columns.tolist())
print(df.head())
print(df.shape)

['id_student', 'code_module', 'code_presentation', 'week', 'weekly_video_clicks', 'weekly_login_frequency', 'weekly_avg_activity_day', 'weekly_avg_quiz_score', 'weekly_assessments_completed', 'weekly_avg_submission_day', 'weekly_avg_assessment_weight', 'dropout']
   id_student code_module code_presentation  week  weekly_video_clicks  \
0        6516         AAA             2014J    -3                  110
1        6516         AAA             2014J    -2                   48
2        6516         AAA             2014J    -1                    2
3        6516         AAA             2014J     0                   96
4        6516         AAA             2014J     1                  229

   weekly_login_frequency  weekly_avg_activity_day  weekly_avg_quiz_score  \
0                       2               -22.461538                    0.0
1                       2               -19.250000                    0.0
2                       1               -12.000000                    0.0
3                       4                -3.090909                    0.0
4                       6                 1.944444                    0.0

   weekly_assessments_completed  weekly_avg_submission_day  \
0                           0.0                        0.0
1                           0.0                        0.0
2                           0.0                        0.0
3                           0.0                        0.0
4                           0.0                        0.0

   weekly_avg_assessment_weight  dropout
0                           0.0        0
1                           0.0        0
2                           0.0        0
3                           0.0        0
4                           0.0        0
(627031, 12)

In [82]:
print(df.groupby("id_student").size().describe())

count    26074.000000
mean        24.048132
std         15.144473
min          1.000000
25%         11.000000
50%         25.000000
75%         34.000000
max        121.000000
dtype: float64

In [83]:
weekly_data.to_csv(

    "../Dataset/weekly_student_dataset.csv",

    index=False

)

print("Weekly Student Dataset Saved Successfully")

Weekly Student Dataset Saved Successfully