In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [5]:
studentVle = pd.read_csv("../Dataset/processed/studentVle_clean.csv")

studentAssessment = pd.read_csv("../Dataset/processed/studentAssessment_clean.csv")

assessments = pd.read_csv("../Dataset/processed/assessments_clean.csv")

studentInfo = pd.read_csv("../Dataset/processed/studentInfo_clean.csv")

In [6]:
print(studentVle.shape)
print(studentAssessment.shape)
print(assessments.shape)
print(studentInfo.shape)

(10655280, 7)
(173912, 5)
(206, 6)
(32593, 13)

In [7]:
studentVle["week"] = (studentVle["date"] // 7) + 1

studentVle.head()

,Unnamed: 0,code_module,code_presentation,id_student,id_site,date,sum_click,week
0,0,AAA,2013J,28400,546652,-10,4,-1
1,1,AAA,2013J,28400,546652,-10,1,-1
2,2,AAA,2013J,28400,546652,-10,1,-1
3,3,AAA,2013J,28400,546614,-10,11,-1
4,4,AAA,2013J,28400,546714,-10,1,-1

In [8]:
weekly_clicks = (

    studentVle

    .groupby(
        [
            "id_student",
            "code_module",
            "code_presentation",
            "week"
        ]
    )["sum_click"]

    .sum()

    .reset_index()

)

weekly_clicks.rename(

    columns={
        "sum_click":"weekly_video_clicks"
    },

    inplace=True

)

weekly_clicks.head()

   id_student code_module code_presentation  week  weekly_video_clicks
0        6516         AAA             2014J    -3                  110
1        6516         AAA             2014J    -2                   48
2        6516         AAA             2014J    -1                    2
3        6516         AAA             2014J     0                   96
4        6516         AAA             2014J     1                  229

In [9]:
assessment_data = pd.merge(

    studentAssessment,

    assessments,

    on="id_assessment",

    how="left"

)

In [10]:
assessment_data["week"] = (

    assessment_data["date_submitted"] // 7

) + 1

In [11]:
weekly_quiz = (

    assessment_data

    .groupby(

        [
            "id_student",
            "code_module",
            "code_presentation",
            "week"
        ]

    )["score"]

    .mean()

    .reset_index()

)

weekly_quiz.rename(

    columns={

        "score":"weekly_avg_quiz_score"

    },

    inplace=True

)

weekly_quiz.head()

   id_student code_module code_presentation  week  weekly_avg_quiz_score
0        6516         AAA             2014J     3                   60.0
1        6516         AAA             2014J     8                   48.0
2        6516         AAA             2014J    17                   63.0
3        6516         AAA             2014J    24                   61.0
4        6516         AAA             2014J    31                   77.0

In [12]:
weekly_assessment = (

    assessment_data

    .groupby(

        [
            "id_student",
            "code_module",
            "code_presentation",
            "week"
        ]

    )

    .size()

    .reset_index(name="weekly_assessments_completed")

)

weekly_assessment.head()

,id_student,code_module,code_presentation,week,weekly_assessments_completed
0,6516,AAA,2014J,3,1
1,6516,AAA,2014J,8,1
2,6516,AAA,2014J,17,1
3,6516,AAA,2014J,24,1
4,6516,AAA,2014J,31,1

In [13]:
weekly_data = pd.merge(

    weekly_clicks,

    weekly_quiz,

    on=[

        "id_student",

        "code_module",

        "code_presentation",

        "week"

    ],

    how="left"

)

weekly_data = pd.merge(

    weekly_data,

    weekly_assessment,

    on=[

        "id_student",

        "code_module",

        "code_presentation",

        "week"

    ],

    how="left"

)

In [14]:
weekly_data = pd.merge(

    weekly_data,

    studentInfo[

        [

            "id_student",

            "code_module",

            "code_presentation",

            "dropout"

        ]

    ],

    on=[

        "id_student",

        "code_module",

        "code_presentation"

    ],

    how="left"

)

In [15]:
weekly_data.fillna(

    {

        "weekly_avg_quiz_score":0,

        "weekly_assessments_completed":0

    },

    inplace=True

)

,id_student,code_module,code_presentation,week,weekly_video_clicks,weekly_avg_quiz_score,weekly_assessments_completed,dropout
0,6516,AAA,2014J,-3,110,0.0,0.0,0
1,6516,AAA,2014J,-2,48,0.0,0.0,0
2,6516,AAA,2014J,-1,2,0.0,0.0,0
3,6516,AAA,2014J,0,96,0.0,0.0,0
4,6516,AAA,2014J,1,229,0.0,0.0,0
...,...,...,...,...,...,...,...,...
627026,2698588,BBB,2014J,33,13,0.0,0.0,0
627027,2698588,BBB,2014J,34,147,0.0,0.0,0
627028,2698588,BBB,2014J,35,12,0.0,0.0,0
627029,2698588,BBB,2014J,36,7,0.0,0.0,0
627030,2698588,BBB,2014J,37,1,0.0,0.0,0

In [16]:
weekly_data = weekly_data.sort_values(

    [

        "id_student",

        "week"

    ]

)

weekly_data.head()

,id_student,code_module,code_presentation,week,weekly_video_clicks,weekly_avg_quiz_score,weekly_assessments_completed,dropout
0,6516,AAA,2014J,-3,110,0.0,0.0,0
1,6516,AAA,2014J,-2,48,0.0,0.0,0
2,6516,AAA,2014J,-1,2,0.0,0.0,0
3,6516,AAA,2014J,0,96,0.0,0.0,0
4,6516,AAA,2014J,1,229,0.0,0.0,0

In [17]:
print(weekly_data.shape)

weekly_data.head()

(627031, 8)

,id_student,code_module,code_presentation,week,weekly_video_clicks,weekly_avg_quiz_score,weekly_assessments_completed,dropout
0,6516,AAA,2014J,-3,110,0.0,0.0,0
1,6516,AAA,2014J,-2,48,0.0,0.0,0
2,6516,AAA,2014J,-1,2,0.0,0.0,0
3,6516,AAA,2014J,0,96,0.0,0.0,0
4,6516,AAA,2014J,1,229,0.0,0.0,0

In [18]:
weekly_data.to_csv(

    "../Dataset/weekly_student_dataset.csv",

    index=False

)

print("Weekly Student Dataset Saved Successfully")

Weekly Student Dataset Saved Successfully